# Production Docker Compose configuration

services:
  pomodoro-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: pomodoro-timer-prod
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
    restart: always
    healthcheck:
      test: ["CMD", "/usr/local/bin/healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - pomodoro-network
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M
    labels:
      - "com.example.description=Pomodoro Timer Production"
      - "com.example.version=1.0.0"
      - "com.example.env=production"

  nginx-proxy:
    image: nginx:alpine
    container_name: pomodoro-nginx-prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/proxy-nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/ssl:/etc/nginx/ssl:ro
    depends_on:
      pomodoro-app:
        condition: service_healthy
    restart: always
    networks:
      - pomodoro-network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 128M

networks:
  pomodoro-network:
    driver: bridge
    name: pomodoro-prod-network